## Problem 1: Lowering Operator in a Three-Level System

**System:** A three-level quantum system (qutrit).

**Tasks:**

1. **State Preparation:** Create the **first excited state** $|1\rangle$ in a 3-level system.

2. **Operator Construction:** Create the **lowering operator** $\hat{a}$ for the same 3-level system.

3. **Operator Action:** Apply the lowering operator to the state and **print the result**.


In [1]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt
state = basis(3,1)
a=destroy(3)
print(a*state)

Quantum object: dims=[[3], [1]], shape=(3, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]
 [0.]]


This is the vector for the state $|0\rangle$. As expected, the lowering operator takes the state $|1\rangle$ and lowers it to the state $|0\rangle$.


## Problem 2: Raising Operator in a Three-Level System

**System:** A three-level quantum system (qutrit).

**Tasks:**

1. **State Preparation:** Create the **first excited state** $|1\rangle$ in a 3-level system.

2. **Operator Construction:** Create the **raising operator** $\hat{a}^\dagger$ for the 3-level system using `destroy(3).dag()`.

3. **Operator Action:** Apply the raising operator to the state and **print the result**.


In [11]:
state = basis(3,1)
a=destroy(3)
b=a.dag()
print(b*state)

Quantum object: dims=[[3], [1]], shape=(3, 1), type='ket', dtype=Dense
Qobj data =
[[0.        ]
 [0.        ]
 [1.41421356]]


We raised the state from $|1\rangle$ to the $|2\rangle$ state. The factor of $\sqrt{2}$ comes from the action of the raising operator, where $\hat{a}^\dagger |n\rangle = \sqrt{n+1}\,|n+1\rangle$. Here, $n = 1$, so $\sqrt{1+1} = \sqrt{2}$.


## Problem 3: Number Operator in a Four-Level System

**System:** A four-level quantum system.

**Tasks:**

1. **State Preparation:** Create the state $|2\rangle$ in a 4-level system.

2. **Operator Construction:** Create the **raising operator** $\hat{a}^\dagger$ and the **lowering operator** $\hat{a}$ for the 4-level system.

3. **Number Operator:** Construct the **number operator** $\hat{n} = \hat{a}^\dagger \hat{a}$.

4. **Operator Action:** Apply the number operator $\hat{n}$ to the state $|2\rangle$ and **print the result**.


In [10]:
state = basis(4,2)
a = destroy(4)
n = a.dag() * a
print(n * state)

Quantum object: dims=[[4], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [2.]
 [0.]]


This shows that the number operator $\hat{n}$ “counts” the excitation level of a state. Since it is applied to the state $|2\rangle$, the result is $2\,|2\rangle$.


## Problem 4: Operator Ordering in a Four-Level System

**System:** A four-level quantum system.

**Tasks:**

1. **Operator Construction:** Create the **raising operator** $\hat{a}^\dagger$ and the **lowering operator** $\hat{a}$ for a 4-level system.

2. **Composite Operator:** Construct the operator $\hat{C} = \hat{a}\hat{a}^\dagger$.

3. **Operator Action:** Apply the operator $\hat{C}$ to the state $|2\rangle$ (i.e., `basis(4, 2)`) and **print the result**.

**Note:**  
This is related to the commutation relation $\,[\hat{a}, \hat{a}^\dagger] = 1$.  
Since $\hat{a}\hat{a}^\dagger - \hat{a}^\dagger\hat{a} = 1$, it follows that  
$\hat{a}\hat{a}^\dagger = \hat{n} + 1$.


In [17]:
a = destroy(4)
a_dag = a.dag()
c= a*a_dag
state = basis(4,2)
print(c*state)

Quantum object: dims=[[4], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [3.]
 [0.]]


As expect from the hint. Since $\hat{a}\hat{a}^\dagger = \hat{n} + 1$ (the number operator plus one), applying it to $|2\rangle$ gives $(\hat{n} + 1)|2\rangle = \hat{n}|2\rangle + |2\rangle = 2|2\rangle + |2\rangle = 3|2\rangle$.


## Problem 5: Superposition State and the Number Operator

**System:** A 10-level quantum system.

**Tasks:**

1. **State Preparation (Ground State):** Create the ground state $|0\rangle$ in a 10-level system.

2. **State Preparation (Excited State):** Create the second excited state $|2\rangle$ in the same 10-level system.

3. **Superposition State:** Create a new state `psi` defined as the sum of the two states:  
   `psi = state0 + state2`.

4. **Number Operator:** Create the **number operator** $\hat{n}$ for the 10-level system.  
   (You may use the built-in function `num(10)` if desired.)

5. **Operator Action:** Apply the number operator $\hat{n}$ to the superposition state `psi` and **print the result**.


In [14]:
state_0 = basis(10,0)
state_2 = basis(10,2)
psi = state_0+state_2
n = num(10)
print(n*psi)

Quantum object: dims=[[10], [1]], shape=(10, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


This happens because the number operator acts on each part of the superposition individually: $\hat{n}(|0\rangle + |2\rangle) = \hat{n}|0\rangle + \hat{n}|2\rangle = (0 \times |0\rangle) + (2 \times |2\rangle) = 2|2\rangle$.


## Problem 6: Qubit Flip with the Pauli $\sigma_x$ Operator

**System:** A two-level quantum system (qubit), with basis states $|0\rangle$ and $|1\rangle$.

**Tasks:**

1. **State Preparation:** Create the ground state $|0\rangle$ for a 2-level system.

2. **Operator Construction:** Create the Pauli $\sigma_x$ operator using `sigmax()`.

3. **Operator Action:** Apply the $\sigma_x$ operator to the ground state $|0\rangle$ and **print the result**.


In [15]:
state_0 = basis(2,0)
sigma_x = sigmax()
print(sigma_x*state_0)

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]]


As expected, the `sigmax()` operator flips the state $|0\rangle$ (the ground state) into the state $|1\rangle$ (the excited state).

## Problem 7: Qubit Flip from the Excited State

**System:** A two-level quantum system (qubit).

**Tasks:**

1. **State Preparation:** Create the excited state $|1\rangle$ for a 2-level system.

2. **Operator Action:** Apply the Pauli $\sigma_x$ operator (`sigmax()`) to the excited state.

3. **Output:** Print the resulting state.


In [16]:
state_1 = basis(2,1)
sigma_x = sigmax()
print(sigma_x*state_1)

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]


As expected, the `sigmax()` operator flips the state $|0\rangle$ (the ground state) into the state $|1\rangle$ (the excited state).


## Problem 8: Action of the Pauli $\sigma_z$ Operator

**System:** A two-level quantum system (qubit).

**Tasks:**

1. **State Preparation (Ground State):** Create the ground state $|0\rangle$ (i.e., `basis(2, 0)`).

2. **Operator Action:** Apply the Pauli $\sigma_z$ operator (`sigmaz()`) to the ground state and **print the result**.

3. **State Preparation (Excited State):** Create the excited state $|1\rangle$ (i.e., `basis(2, 1)`).

4. **Operator Action:** Apply the Pauli $\sigma_z$ operator to the excited state and **print the result**.


In [18]:
state_0 = basis(2,0)
sigma_z = sigmaz()
print(sigma_z*state_0)
state_1 = basis(2,1)
print(sigma_z*state_1)

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]]
Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[ 0.]
 [-1.]]


When `sigmaz()` acts on $|0\rangle$, it returns $|0\rangle$ multiplied by $+1$. When `sigmaz()` acts on $|1\rangle$, it returns $|1\rangle$ multiplied by $-1$.


## Problem 9: Action of $\sigma_z$ on a Superposition State

**System:** A two-level quantum system (qubit).

**Tasks:**

1. **State Preparation (Up):** Create the state $|0\rangle$ (call it `up`).

2. **State Preparation (Down):** Create the state $|1\rangle$ (call it `down`).

3. **Superposition State:** Create the superposition state `psi = up + down`.

4. **Operator Action:** Apply the Pauli $\sigma_z$ operator (`sigmaz()`) to the superposition state `psi` and **print the result**.


In [19]:
up = basis(2,0)
down = basis(2,1)
psi = up + down
sigma_z = sigmaz()
print(sigma_z*psi)

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[ 1.]
 [-1.]]


The state $|0\rangle - |1\rangle$ is an eigenstate of a different operator, $\sigma_x$, with an eigenvalue of $-1$.


## Problem 10: Expectation Value of $\sigma_z$ for a Superposition State

**System:** A two-level quantum system (qubit).

**Tasks:**

1. **Superposition State:** Create the state `psi = basis(2, 0) + basis(2, 1)`.

2. **Normalization:** Normalize the state 

3. **Expectation Value:** Calculate and print the expectation value of the Pauli $\sigma_z$ operator for the normalized state using `expect(sigmaz(), psi_norm)`.


In [ ]:
state0 = basis(2, 0)
state1 = basis(2, 1)
psi = state0 + state1
psi_norm = psi.unit() 

avg_value = expect(sigmaz(), psi_norm)

print(avg_value)

0.0


It means the expectation value is exactly zero.

## Problem 11: Hermitian Operators and Qobj Attributes

**System:** A four-level quantum system.

**Tasks:**

1. **Operator Construction (Lowering Operator):** Create the lowering operator $\hat{a}$ for a 4-level system.

2. **Hermiticity Check:** Print the `.isherm` attribute of the lowering operator.

3. **Operator Construction (Number Operator):** Create the number operator $\hat{n} = \hat{a}^\dagger \hat{a}$ for the 4-level system.

4. **Hermiticity Check:** Print the `.isherm` attribute of the number operator.


In [25]:
a = destroy(4)
print("Lowering operator 'a' is Hermitian:", a.isherm)
n = a.dag()*a
print("Number operator 'n' is Hermitian:", n.isherm)

Lowering operator 'a' is Hermitian: False
Number operator 'n' is Hermitian: True


## Problem 12: The Qubit “Plus” State and the $\sigma_x$ Operator

**System:** A two-level quantum system (qubit).

**Tasks:**

1. **State Preparation:** Create the ground state $|0\rangle$ and the excited state $|1\rangle$ for a 2-level system.

2. **Superposition State:** Create the state `psi = state0 + state1`.

3. **Normalization:** Create the normalized “plus” state by applying the `.unit()` method to `psi`.

4. **Operator Action:** Apply the Pauli $\sigma_x$ operator (`sigmax()`) to the normalized “plus” state and **print the result**.


In [28]:
state_0 = basis(2,0)
state_1 = basis(2,1)
psi = state_0 + state_1
psi_norm = psi.unit()
operation = sigmax()*psi_norm
print(operation)

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.70710678]
 [0.70710678]]


The `sigmax()` operator acts just like a classical NOT gate:

- It flips $|0\rangle \rightarrow |1\rangle$.
- It flips $|1\rangle \rightarrow |0\rangle$.

So when it is applied to the “plus” state $(|0\rangle + |1\rangle)/\sqrt{2}$, we get  
$\sigma_x\!\left((|0\rangle + |1\rangle)/\sqrt{2}\right) = (\sigma_x|0\rangle + \sigma_x|1\rangle)/\sqrt{2} = (|1\rangle + |0\rangle)/\sqrt{2}$.

This is exactly the same state we started with, showing that the plus state is an eigenstate of $\sigma_x$ with eigenvalue $+1$.


## Problem 13: The Qubit “Minus” State and the $\sigma_x$ Operator

**System:** A two-level quantum system (qubit).

**Tasks:**

1. **State Preparation:** Create the ground state $|0\rangle$ and the excited state $|1\rangle$ for a 2-level system.

2. **Minus State:** Create the “minus” state  
   $\psi = |0\rangle - |1\rangle$,  
   and normalize it using the `.unit()` method.

3. **Operator Action:** Apply the Pauli $\sigma_x$ operator (`sigmax()`) to the normalized “minus” state and **print the result**.


In [29]:
state_0 = basis(2,0)
state_1 = basis(2,1)
psi = state_0 - state_1
psi_norm = psi.unit()
operation = sigmax()*psi_norm
print(operation)

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[-0.70710678]
 [ 0.70710678]]


Just like before, applying `sigmax()` to the “minus” state returns the same state, but this time multiplied by $-1$.


## Problem 14: Action of the Pauli $\sigma_y$ Operator on the “Plus” State

**System:** A two-level quantum system (qubit).

**Tasks:**

1. **Plus State:** Create the “plus” state  
   `psi_plus = (basis(2, 0) + basis(2, 1)).unit()`.

2. **Operator Action:** Apply the Pauli $\sigma_y$ operator (`sigmay()`) to `psi_plus` and **print the result**.


In [30]:
state_0 = basis(2,0)
state_1 = basis(2,1)
psi = state_0 - state_1
psi_norm = psi.unit()
operation = sigmay()*psi_norm
print(operation)

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.+0.70710678j]
 [0.+0.70710678j]]


So, the “plus” state is not an eigenstate of `sigmay()` because the original state $(|0\rangle + |1\rangle)/\sqrt{2}$ is not just a number times the new state $(-i|0\rangle + i|1\rangle)/\sqrt{2}$. The $\sigma_y$ operator changes the “plus” state into a completely different state.


## Problem 15: Eigenstate of the Pauli $\sigma_y$ Operator

**System:** A two-level quantum system (qubit).

**Tasks:**

1. **State Preparation:** Create the state  
   $|\psi\rangle = (|0\rangle + i|1\rangle)/\sqrt{2}$

2. **Operator Action:** Apply the Pauli $\sigma_y$ operator to this state.

3. **Output:** Print the resulting state.


In [36]:
state = basis(2,0)+1j*basis(2,1)
psi = state.unit()
print(sigmay()*psi)


Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.70710678+0.j        ]
 [0.        +0.70710678j]]


Because applying `sigmay()` to the state $(|0\rangle + i|1\rangle)/\sqrt{2}$ returns the exact same state, this state is an eigenstate of $\sigma_y$ with an eigenvalue of $+1$.


## Problem 16: Second Eigenstate of the Pauli $\sigma_y$ Operator

**System:** A two-level quantum system (qubit).

**Tasks:**

1. **State Preparation:** Create the state  
   $|\psi\rangle = (|0\rangle - i|1\rangle)/\sqrt{2}$  

2. **Operator Action:** Apply the Pauli $\sigma_y$ operator to this state.

3. **Output:** Print the resulting state.


In [37]:
state = basis(2,0)-1j*basis(2,1)
psi = state.unit()
print(sigmay()*psi)


Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[-0.70710678+0.j        ]
 [ 0.        +0.70710678j]]


This means that the state $(|0\rangle - i|1\rangle)/\sqrt{2}$ is the other eigenstate of $\sigma_y$, with an eigenvalue of $-1$.


## Problem 17: Density Matrix of the Ground State

**System:** A two-level quantum system (qubit).

**Tasks:**

1. **State Preparation:** Create the ground state ket $|0\rangle$ for a 2-level system.

2. **Density Matrix:** Use this ket to construct the density matrix  
   $\rho = |0\rangle\langle 0|$.

3. **Output:** Print the resulting density matrix.


In [43]:
psi_0 = basis(2,0)
rho = psi_0*psi_0.dag() # or rho = fock_dm(2,0)
print(rho)

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[1. 0.]
 [0. 0.]]


## Problem 18: Mixed State Density Matrix

**System:** A two-level quantum system (qubit).

**Tasks:**

1. **Ground State Density Matrix:** Create the density matrix for the ground state using  
   `dm0 = fock_dm(2, 0)`.

2. **Excited State Density Matrix:** Create the density matrix for the excited state using  
   `dm1 = fock_dm(2, 1)`.

3. **Mixed State:** Combine these to create the mixed state $\rho$ described above.

4. **Output:** Print the resulting density matrix.


In [45]:
dm_0 = fock_dm(2,0)
dm_1 = fock_dm(2,1)
dm_mixed = 0.5*dm_0+0.5*dm_1
print(dm_mixed)

Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0.5 0. ]
 [0.  0.5]]


The diagonal elements represent the classical probabilities of each basis state. This density matrix indicates a 50% probability that the system is in the state $|0\rangle$ and a 50% probability that it is in the state $|1\rangle$.


## Problem 19: Thermal State Density Matrix

**System:** A five-level quantum system.

**Tasks:**

1. **Thermal State:** Create the thermal state density matrix for a 5-level system with an average excitation number of 1.25.

2. **Output (Full Density Matrix):** Print the resulting density matrix.

3. **Diagonal Elements:** Print only the diagonal elements of the density matrix using the `.diag()` method.  
   (These elements give the probabilities of finding the system in the states $|0\rangle, |1\rangle, |2\rangle$, and so on.)


In [49]:
rho_thermal = thermal_dm(5,1.25)
print("Full density matrix is :",rho_thermal)
print("\nDiagonal elements (probabilities):",rho_thermal.diag())

Full density matrix is : Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=Dia, isherm=True
Qobj data =
[[0.46927974 0.         0.         0.         0.        ]
 [0.         0.26071096 0.         0.         0.        ]
 [0.         0.         0.14483942 0.         0.        ]
 [0.         0.         0.         0.08046635 0.        ]
 [0.         0.         0.         0.         0.04470353]]

Diagonal elements (probabilities): [0.46927974 0.26071096 0.14483942 0.08046635 0.04470353]


This means that `_dm` creates a density matrix. The second argument is simply the key parameter defining the state, which only in the case of `thermal_dm` happens to be an expectation value.


## Problem 20: Different Meanings of Raising Operators

**System:** A two-level quantum system.

**Tasks:**

1. **Ground State:** Create the ground state `vac = basis(2, 0)`.

2. **Oscillator Raising Operator:** Create the harmonic oscillator raising operator `c = create(2)`.

3. **Operator Action (Oscillator):** Apply `c` to `vac` and **print the result**.

4. **Spin Raising Operator:** Create the spin raising operator `sp = sigmap()`.

5. **Operator Action (Spin):** Apply `sp` to the same `vac` state and **print the result**.


In [53]:

state_0 = basis(2,0)
a = create(2)
b = a*state
sp = sigmap()
c = sp*state_0
print(b)
print(c)

Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [1.]]
Quantum object: dims=[[2], [1]], shape=(2, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]]


So, even though basis(2, 0) is the same vector, the operators create(2) and sigmap() treat it differently because they belong to different physical models (oscillator vs. spin).

## Problem 21: Expectation Value of the Number Operator

**System:** A five-level quantum system.

**Tasks:**

1. **Number Operator:** Create the number operator $\hat{n}$ for a 5-level system (you may use `num(5)`).

2. **State Preparation:** Create the third excited state $|3\rangle$ (i.e., `basis(5, 3)`).

3. **Expectation Value:** Calculate the expectation value of the number operator $\hat{n}$ for the state $|3\rangle$.

4. **Output:** Print the result.


In [54]:
n = num(5)
state_3 = basis(5, 3)
a = expect(n, state_3)
print(a)

3.0


The state is $|3\rangle$, so when the particle number is measured using the number operator $\hat{n}$, the expectation value (and, in this case, the only possible measurement outcome) is exactly $3.0$.


## Problem 22: Expectation Values for a List of States

**System:** A five-level quantum system.

**Tasks:**

1. **State List:** Create a list of the first five Fock states, from $|0\rangle$ to $|4\rangle$, in a 5-level system. 

2. **Number Operator:** Create the number operator $\hat{n} = \texttt{num(5)}$.

3. **Expectation Values:** Calculate the expectation value of $\hat{n}$ for the list of states.

4. **Output:** Print the resulting list of expectation values.


In [2]:
states = [basis(5,i) for i in range (5)]
n = num(5)
print(expect(n,states))

[0. 1. 2. 3. 4.]


When you run `print(expect(n, states))`, QuTiP automatically computes the expectation value of the operator for each state in the list and returns a list of results. In this case, the output is `[0. 1. 2. 3. 4.]`.


## Problem 23: The Harmonic Superposition

**System:** A 10-level Harmonic Oscillator ($N=10$).

**Tasks:**

1.  **Create the State:** Create an *unnormalized* superposition state `psi` that is the sum of the first excited state $|1\rangle$ and the third excited state $|3\rangle$.
2.  **Normalize:** Create a normalized version of this state called `psi_norm`.
3.  **Operator:** Create the **number operator** $\hat{n}$ for this system.
4.  **Expectation:** Calculate the **expectation value** of $\hat{n}$ for your normalized state `psi_norm`.
    * *Mental Check:* Since it's an equal mix of $|1\rangle$ and $|3\rangle$, what should the average be?
5.  **Density Matrix:** Create the density matrix `rho` corresponding to `psi_norm` and check if it is Hermitian using the `.isherm` attribute.

In [4]:
psi = basis(10,1)+basis(10,3)
psi_norm = psi.unit()
n = num(10)
expectation = expect(n,psi_norm)
print(f"Expectation Value: {expectation}")
rho = psi_norm * psi_norm.dag()
print(f"Is Hermitian? {rho.isherm}")
print(rho)

Expectation Value: 1.9999999999999996
Is Hermitian? True
Quantum object: dims=[[10], [10]], shape=(10, 10), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.5 0.  0.5 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.5 0.  0.5 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]]
